# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 5000
  max-http-header-size: 102400
