# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cache:
    type: redis
  redis:
    # 数据库索引 默认为0
    database: 0
    # redis服务器地址
    host: 49.234.221.187
    # redis端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    cache-enabled: true
server:
  port: 5000
  max-http-header-size: 102400
logging:
  level:
    com.kanouakira.vueblog.mapper: trace